name: Build NothingOSS Kernel

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      kpm_support:
        description: 'Enable KPM support'
        required: false
        type: boolean
        default: true
      susfs_support:
        description: 'Enable SUSFS support'
        required: false
        type: boolean
        default: true
      bbg_support:
        description: 'Enable BBG support'
        required: false
        type: boolean
        default: true
      susfs_force:
        description: 'Force SUSFS patch apply (ignore failures)'
        required: false
        type: boolean
        default: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      kernel_repo: https://github.com/NothingOSS/android_kernel_msm-5.10_nothing_sm8475.git
      kernel_branch: sm8475/b/mr
      kernel_defconfig: gki_defconfig
      extra_configs: 'vendor/waipio_GKI.config'
      susfs_branch: gki-android13-5.10
      kpm_support: ${{ inputs.kpm_support }}
      susfs_support: ${{ inputs.susfs_support }}
      susfs_force: ${{ inputs.susfs_force }}
      bbg_support: ${{ inputs.bbg_support }}
